apiVersion: v1
kind: Secret
metadata:
  name: elos-google-search-secret
  labels:
    app: elos-google-search-mcp
type: Opaque
data:
  # Base64 encoded values - replace with actual base64 encoded values
  google-api-key: <base64-encoded-api-key>
  google-cse-id: <base64-encoded-cse-id>
  google-credentials: <base64-encoded-service-account-json>
stringData:
  # These are the actual values (not base64 encoded)
  google-api-key: "your-google-api-key-here"
  google-cse-id: "your-google-custom-search-engine-id-here"
  # For service account authentication, paste the entire JSON content
  google-credentials: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "your-private-key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
      "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
      "client_id": "your-client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"
    }
