apiVersion: apps/v1
kind: Deployment
metadata:
  name: elos-google-search-mcp
  labels:
    app: elos-google-search-mcp
    component: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elos-google-search-mcp
  template:
    metadata:
      labels:
        app: elos-google-search-mcp
        component: mcp-server
    spec:
      containers:
      - name: elos-google-search-mcp
        image: quay.io/elostech/elos-mcp-google-search:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: elos-google-search-secret
              key: google-api-key
        - name: GOOGLE_CSE_ID
          valueFrom:
            secretKeyRef:
              name: elos-google-search-secret
              key: google-cse-id
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials/google-credentials.json"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: google-credentials
          mountPath: /app/credentials
          readOnly: true
      volumes:
      - name: google-credentials
        secret:
          secretName: elos-google-search-secret
          items:
          - key: google-credentials
            path: google-credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: elos-google-search-mcp-service
  labels:
    app: elos-google-search-mcp
spec:
  selector:
    app: elos-google-search-mcp
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
